# MIT License
#
# Copyright (c) 2022 Joker2770
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: doukutsu-rs
version: 0.99.0-beta4
summary: A fully playable re-implementation of Cave Story engine written in Rust.
description: |
  A fully playable re-implementation of Cave Story (Doukutsu Monogatari) engine written in Rust.

  _More build details: https://github.com/Joker2770/doukutsu-rs-snap.git_

base: core20
grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/lib/dri:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
  doukutsu-rs:
    after: [alsa-mixin]
    plugin: rust
    source: https://github.com/doukutsu-rs/doukutsu-rs.git
    source-type: git
    source-branch: master
    build-packages:
      - pkg-config
      - gcc
      - g++
      - cmake
      - make
      - libasound2-dev
      - libsdl2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - libsdl2-2.0-0
      - libpulse0
      - libgl1
      - libgl1-mesa-dri
  game-data:
    after: [doukutsu-rs]
    plugin: dump
    source: https://github.com/doukutsu-rs/game-data.git
    source-type: git
    source-branch: master
    organize:
      '*': bin/data/

apps:
  doukutsu-rs:
    command: bin/doukutsu-rs
    environment:
      # pulseaudio
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
    plugs:
      - home
      - audio-playback
      - alsa
      - pulseaudio
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - removable-media
      - joystick
