# MIT License
#
# Copyright (c) 2022-2025 Joker2770
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: doukutsu-rs
version: 0.101.0-beta6
summary: A fully playable re-implementation of Cave Story engine written in Rust.
description: |
  A fully playable re-implementation of Cave Story (Doukutsu Monogatari) engine written in Rust.

  _More build details: https://github.com/Joker2770/doukutsu-rs-snap.git_

base: core24
grade: stable
confinement: strict

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.0
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1
  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

plugs:
    desktop:
        mount-host-font-cache: false
    gtk-3-themes:
        interface: content
        target: $SNAP/data-dir/themes
        default-provider: gtk-common-themes
    icon-themes:
        interface: content
        target: $SNAP/data-dir/icons
        default-provider: gtk-common-themes
    sound-themes:
        interface: content
        target: $SNAP/data-dir/sounds
        default-provider: gtk-common-themes
    gnome-46-2404:
        interface: content
        target: $SNAP/gnome-platform
        default-provider: gnome-46-2404
    # gpu-2404:
    #     interface: content
    #     target: $SNAP/gpu-2404
    #     default-provider: mesa-24040

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
  doukutsu-rs:
    after: [alsa-mixin]
    plugin: rust
    rust-features: ["backend-sdl"]
    source: https://github.com/doukutsu-rs/doukutsu-rs.git
    source-type: git
    source-branch: master
    build-packages:
      - pkg-config
      - gcc
      - g++
      - cmake
      - make
      - libsdl2-dev
      - libasound2-dev
      - libudev-dev
      - libgl1-mesa-dev
    stage-packages:
      - libsdl2-2.0-0
      - libmodplug1
      - libopusfile0
      - libpulse0
      - libsndfile1
      - libgl1
      - libgl1-mesa-dri
      - libglu1-mesa
  game-data:
    after: [doukutsu-rs]
    plugin: dump
    source: https://github.com/doukutsu-rs/game-data.git
    source-type: git
    source-branch: master
    organize:
      '*': bin/data/

apps:
  doukutsu-rs:
    command: bin/doukutsu-rs
    command-chain: ["snap/command-chain/alsa-launch"]
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/local/lib
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      GTK_USE_PORTAL: '1'
    extensions: [gnome]
    plugs:
      - home
      - audio-playback
      - alsa
      - pulseaudio
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - removable-media
      - joystick
      - gsettings
      - mount-observe
